# Site settings
title: Coinskro Docs
description: "Developer documentation for Coinskro products â€” payments, wallets, and more"
baseurl: "/coinskro-pay-testnet"
url: "https://Coinskro.github.io"

# Theme settings
remote_theme: just-the-docs/just-the-docs
color_scheme: coinskro

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Search settings
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive

# Footer
footer_content: "Copyright &copy; 2024-2026 Coinskro. Distributed under the MIT license."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links (top right navigation)
aux_links:
  "Dashboard":
    - "https://coinskro.com"

aux_links_new_tab: true

# Heading anchor links
heading_anchors: true

# Code copy button
enable_copy_code_button: true

# Callouts
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: green
